### ISSUE TITLE
Warning: format string arg mismatch (`vpu-count.c`:504-510)

### ISSUE THREAD

**Issue by rvuduc** [jeffhammond/vpu-count#13]
When `DEBUG` is enabled, the following print generates a compile-time warning due to format argument mismatch (1 placeholder for 2 args, lines 504-510 of `vpu-count.c`). Presumably `Cooper Lake` → `Cooper Lake (%s)` (to match `cpu_name`)?

```c
            /* Cooper Lake: Intel(R) Xeon(R) Platinum _3__H... */
            if (cpu_name[23] == '3') {
#ifdef DEBUG
                fprintf(stderr,"Cooper Lake detected, BF16 %s\n", cpu_name,
                        has_avx512_bf16() ? "found" : "not found" );
#endif
                return 2;
            }
```

**Comment by jeffhammond** [comment]
Thanks for reporting this!  I haven't tested on Cooper Lake and apparently am not doing a good job testing with `DEBUG=1`.
