### ISSUE TITLE
W- series mis-identified

### ISSUE THREAD

**Issue by loveshack** [jeffhammond/vpu-count#2]
The vpu_count code gets my workstation SKX wrong, which is reported (under Debian stable -- I don't know if it's software dependent) as

Intel(R) Xeon(R) W-2123 CPU @ 3.60GHz

It looks for the W in the wrong position, so presumably there should be another case looking at  cpu_name[17].

**Comment by jeffhammond** [comment]
I have never had access to Xeon W systems, so I was going off of what I found documented for the processor name.  I pushed a fix now.  Please confirm it works.

**Comment by loveshack** [comment]
That change works for my W-2123 system.

See also changes to https://github.com/flame/blis/pull/351 in case it's
helpful if you want to update your code.

**Comment by jeffhammond** [comment]
@loveshack I think I've done all the necessary updates so far.  I've had Cascade Lake Xeon Scalable processor support in there for a while and just added the W/D/i9 support just now.
