### ISSUE TITLE
D- series not included

### ISSUE THREAD

**Issue by loveshack** [jeffhammond/vpu-count#3]
In case they're relevant, ARK has Skylake D- processors with one FMA, in addition to the ones listed here.

It seems challenging to have to keep up with new processor listings...  Presumably there's nothing one can assume about future processors.

**Comment by jeffhammond** [comment]
Can you try again?  I pushed the update for Xeon D-21xx based upon what I see in ARK.

This is an unofficial, best effort project that exists primarily to serve as documentation for linear algebra library developers like the BLIS team.  I wasn't aware that anyone actually used it, so I haven't made an effort to keep it up-to-date.

It should be straightforward for me to add Cascade Lake support in the near future, but I only have access to the 8268 parts right now, so I'll have to continue to go off of ARK for processor names and FMA counts.

**Comment by loveshack** [comment]
> Can you try again?  I pushed the update for Xeon D-21xx based upon
> what I see in ARK.

Sorry, I don't have D -- I just noticed it in the ARK list.  I'll check W.

> This is an unofficial, best effort project that exists primarily to
> serve as documentation for linear algebra library developers like the
> BLIS team.

Sure.  I only found it in that context when looking for info.

> It should be straightforward for me to add Cascade Lake support in the
> near future, but I only have access to the 8268 parts right now, so
> I'll have to continue to go off of ARK for processor names and FMA
> counts.

I've got part-way through the list for bli_cpuid if that saves you the
trouble.

**Comment by jeffhammond** [comment]
I added Skylake D support, but I'm not sure it's right.  ARK says it has 1 FMA but LINPACK testing suggests otherwise.  As I work for Intel, I'm not going to question ARK until I have incontrovertible evidence that it's wrong.
