### ISSUE TITLE
add Ice Lake client support

### ISSUE THREAD

**Issue by jeffhammond** [jeffhammond/vpu-count#4]
Ask Ed for help with testing...

**Comment by Wunkolo** [comment]
Would it be possible to have a precompiled version of this in the github releases?
I would love to contribute some *lake values(I recently acquired the elusive Icelake processor) and would love to contribute to any gaps that databases like this might have.
AFAIK: Icelake accomplishes AVX512 with a curious mixture of 256-bit vector units.
![](https://cdn.mos.cms.futurecdn.net/XakmcecM8euMZ7Co52iBhG-970-80.jpg)

**Comment by jeffhammond** [comment]
@Wunkolo Thank you for your willingness to contribute.  I got access to an Ice Lake client test system two days ago and pushed what I think are the necessary changes for Ice Lake client yesterday (https://github.com/jeffhammond/vpu-count/pull/10).  Because the Intel optimization guide says that all client parts have 1 FMA, I shouldn't need to test different SKUs.  However, unverified assumptions are bad and more testing is always good, so I will put a release out for you.

Right now, the only systems I use are 64-bit Linux and MacOS.  I don't know how to do anything code related with Windows, although I suppose I can try to learn.  Are you content with a Linux binary?

**Comment by jeffhammond** [comment]
@Wunkolo Please try https://github.com/jeffhammond/vpu-count/releases/tag/1.  Today was my first day ever creating a GitHub release and this is my first even release binary, so please forgive any idiotic errors.

**Comment by Wunkolo** [comment]
Here's my results from an [i7-1065G7](https://en.wikichip.org/wiki/intel/core_i7/i7-1065g7). Worked totally fine on my portable/persistant Arch Linux install.
```
0x0: 1b,756e6547,6c65746e,49656e69
Intel? yes
0x1: 706e5,4100800,7ffafbbf,bfebfbff
signature:  0x0706e5
model:      0x7e=126
family:     0x06=6
ext model:  0x07=7
Skylake server? no
0x1: 706e5,4100800,7ffafbbf,bfebfbff
signature:  0x0706e5
model:      0x7e=126
family:     0x06=6
ext model:  0x07=7
Ice Lake client? yes
Ice Lake client detected
cpu_name = Intel(R) Core(TM) i7-1065G7 CPU 
0x7: 0,f2bf27ef,40405f5e,bc000410
AVX-512 F,CD,DQ,BW,VL detected
0x7: 0,f2bf27ef,40405f5e,bc000410
AVX-512 VPOPCNTDQ detected
0x7: 0,f2bf27ef,40405f5e,bc000410
AVX-512 VBMI2,GFNI,VAES,VPCLMULQDQ,BITALG detected
CPU has 1 AVX-512 VPUs
```

**Comment by jeffhammond** [comment]
Thanks! That’s the same as I see on my Ice Lake system.
