### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by jeffhammond** [jeffhammond/vpu-count#5]
@loveshack do you have access to lots of these machines to test vpu-count?  I'm sure you'll be amused to know that I have access to very few variants of Intel CPUs - usually the top bins - and I would love it if there was a way to test vpu-count more broadly.

**Comment by loveshack** [comment]
> @loveshack do you have access to lots of these machines to test
> vpu-count?

Afraid not, just a W- box and Gold servers locally.  I was just led down
this rabbit hole by getting the wrong results with the workstation system.
